### ISSUE TITLE
no module

### ISSUE THREAD

**Issue by BULLET7171** [ilyBenny/selfcord#1]
Exception has occurred: ModuleNotFoundError
No module named 'selfcord.user'

i imported selfcord i even tried to install this selfcord.user thing but didn't work

**Comment by ilyBenny** [comment]
Try importing `selfcord.User`.

**Comment by BULLET7171** [comment]
doesn't work mate.
it says selfcord.User could not be resolved (module not found)

**Comment by ilyBenny** [comment]
try doing this `from selfcord import User`

**Comment by BULLET7171** [comment]
![image](https://user-images.githubusercontent.com/73592600/126034839-8c0c374d-14bc-4233-b0a8-71fc007c2644.png)
i did from selfcord import User

**Comment by ilyBenny** [comment]
In selfcord you don't use it like that, take a look at the examples.
