### ISSUE TITLE
help please

### ISSUE THREAD

**Issue by BULLET7171** [ilyBenny/selfcord#2]
dude i tried to do the same thing as shown in the example

import discord
import selfcord
from discord.ext import commands

bot = commands.Bot(command_prefix=".", self_bot=True)
selfcord.login("mfa.V6W_0451oqBGXZQUmZsh")

@bot.event
async def on_ready():
    print("Selfcord Example Selfbot Online.")
    print("Use the prefix '.' to control the bot")

@bot.command(name="changetheme", usage="[light/dark]")
async def changetheme(ctx, theme):
    selfcord.User.setTheme(theme)
    selfcord.Messages.sendMessage(f"Changed your Discord client theme to `{theme}`.", ctx.channel.id)

@bot.command(name="customstatus", usage="[text]")
async def customstatus(ctx, *, text):
    selfcord.User.setCustomStatus(text)
    selfcord.Messages.sendMessage(f"Changed your Discord custom status to `{text}`.", ctx.channel.id)

bot.run("mfa.V6WTKVZsh", bot=False) still it says selfcord.user not found would you mind adding me BULLET#1000 on discord?

**Comment by ilyBenny** [comment]
Use your full token.

**Comment by BULLET7171** [comment]
> Use your full token.
it is my full token i removed some words from it to show it to you

**Comment by ilyBenny** [comment]
It was working for me but I'll try again and get back to you, you might be getting issues since you have 2fa enabled.

**Comment by BULLET7171** [comment]
it doesn't work without 2fa as well, can i just get your uhh alt discord or something we can talk there

**Comment by ilyBenny** [comment]
Please make sure you are using latest version of selfcord.
